rethinkdb:
  image: rethinkdb
  # Local development purpose
  # ports:
    # - "28015:28015"
    # - "8080:8080"
horizon:
  image: rethinkdb/horizon
  volumes:
    - ./:/usr/app
  environment:
    - RETHINKDB_URI=rethinkdb://rethinkdb:28015
  links:
    - rethinkdb